sudo: false
language: python
dist: xenial
matrix:
  include:
  - python: '3.6'
    env: TOXENV=py36-1.11
  - python: '3.6'
    env: TOXENV=py36-2.0
  - python: '3.6'
    env: TOXENV=py36-2.1
  - python: '3.6'
    env: TOXENV=py36-2.2
  - python: '3.6'
    env: TOXENV=py36-master
  - python: '3.7'
    env: TOXENV=py37-1.11
  - python: '3.7'
    env: TOXENV=py37-2.0
  - python: '3.7'
    env: TOXENV=py37-2.1
  - python: '3.7'
    env: TOXENV=py37-2.2
  - python: '3.7'
    env: TOXENV=py37-master
install:
- pip install coveralls tox>=3
script:
- tox
after_script:
- coveralls
deploy:
  provider: pypi
  user: __token__
  password:
    secure: Xr1gkV74umDeBc7lnLm1DWoLa0PDIAYB8HFvnr+aUNkFinD2RLYop6IUO+wvrrk/2sE88rREomD4VbS1kaq+tvCBIz1oh6q3oZZdz5J0PWiPAZ2KD/H5K1U+p6S3xgf6k3diGFr54wBflha5GkX+Gt2Xc/fr0XEkEKsDlAbWBCjz3XCmg022tE8kO3wBN35BgKXog6IVYvnhvbvNF7yeKhTGgzC2ZkEpYjMi0rusooH82/pnOwbsdDul/6iM2qS1yVy8NIbozGKX4XwcdztTCvDiFPEO0+HO8r+ud7/7DQuTHhyVAjOlizPrm8FC/qWxt3EOe+G6F/4xR7BtXEBdXlLDI8jPPGqeZ1WiCxf6VD85njAjf1KUEyM7FSxylmNIZYILW7P5KwoQwcrNsUKC67XshktolZJ/cq/HkZmq23XS6FlPUBdiM3VWsv+jGsJtx58Golz8Gv/fIDosdKa1uo+NFBY4po/uypfqsXfnVGA0tpAVEA1bQmG7N2MupBC9mdJIZam8olo8f/mPbK/77KqbnzlJ4s/WOhd3luaMTeyzFpBz6xrRGlIDOIZlOD7GBrbVrIpZEuD7LbqrOVXsdOwIuOmcWd2XuNVzywNiNLwzZmnvxiXWBit82JcqQvdla8B8K4nDaAZ96qR4JfeOMlSs0kq6CSP1hKMVOYJ1t5E=
  distributions: sdist bdist_wheel
  on:
    tags: true
    skip_existing: true
