name: Tests and create release

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.8"
          - "3.9"
          - "3.10"
        django-version:
          - "3.2"
          - "4.0"
          - "4.1"

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - run: python -m pip install -r requirements.txt
      - run: python -m pip install Django~="${{ matrix.django-version }}"
      - run: python -m pip install -e .
      - run: python -m pytest --cov=login_required --cov-report=term-missing --cov-report=xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          flags: py${{ matrix.python-version }}
          name: tests

  changerelease:
    needs: tests
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' }}
    steps:
      - name: Create Release
        uses: dropseed/changerelease@v1
        with:
          github_token: ${{ secrets.MY_GITHUB_TOKEN }}
